# Generated by Django 4.2.27

import core.fields
import core.models.base_mutation
import core.utils
import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='NoticeID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='NoticeUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('title', models.CharField(db_column='Title', max_length=255)),
                ('description', models.TextField(db_column='Description')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], db_column='Priority', default='MEDIUM', max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='CreatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='UpdatedAt')),
                ('schedule_publish', models.BooleanField(db_column='SchedulePublish', default=False)),
                ('publish_start_date', models.DateTimeField(blank=True, db_column='PublishStartDate', null=True)),
                ('is_active', models.BooleanField(db_column='IsActive', default=True)),
                ('health_facility', models.ForeignKey(blank=True, db_column='HFID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='location.healthfacility')),
            ],
            options={
                'db_table': 'tblNotices',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('validity_from', core.fields.DateTimeField(db_column='ValidityFrom', default=datetime.datetime.now)),
                ('validity_to', core.fields.DateTimeField(blank=True, db_column='ValidityTo', null=True)),
                ('legacy_id', models.IntegerField(blank=True, db_column='LegacyID', null=True)),
                ('id', models.AutoField(db_column='AttachmentID', primary_key=True, serialize=False)),
                ('uuid', models.CharField(db_column='AttachmentUUID', default=uuid.uuid4, max_length=36, unique=True)),
                ('general_type', models.CharField(choices=[('FILE', 'File'), ('URL', 'URL')], db_column='GeneralType', default='FILE', help_text='Indicates whether this is a file attachment or a URL link.', max_length=4)),
                ('type', models.TextField(blank=True, db_column='Type', help_text='Custom type description if needed.', null=True)),
                ('title', models.TextField(blank=True, db_column='Title', help_text='Title or name of the attachment.', null=True)),
                ('date', core.fields.DateField(blank=True, db_column='Date', default=core.utils.TimeUtils.now, help_text='Date of the attachment.')),
                ('filename', models.TextField(blank=True, db_column='Filename', help_text='Original filename of the uploaded file.', null=True)),
                ('mime', models.TextField(blank=True, db_column='Mime', help_text="MIME type of the file (e.g., 'application/pdf').", null=True)),
                ('module', models.TextField(db_column='Module', default='notice', help_text='Module identifier for future core integration.', null=True)),
                ('url', models.TextField(blank=True, db_column='URL', help_text="URL link to the attachment if general_type is 'URL'.", null=True)),
                ('document', models.TextField(blank=True, db_column='Document', help_text="Base64-encoded file content if general_type is 'FILE'.", null=True)),
                ('notice', models.ForeignKey(db_column='NoticeID', on_delete=django.db.models.deletion.CASCADE, related_name='notice_attachments', to='notice.notice')),
            ],
            options={
                'db_table': 'tblNoticeAttachments',
            },
            bases=(core.utils.CachedModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='NoticeMutation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mutation', models.ForeignKey(db_column='MutationLogID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_category', to='core.mutationlog')),
                ('notice', models.ForeignKey(db_column='NoticeID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='notice_mutations', to='notice.notice')),
            ],
            options={
                'db_table': 'notice_NoticeMutation',
                'managed': True,
            },
            bases=(models.Model, core.models.base_mutation.ObjectMutation),
        ),
    ]
