# Generated by Django 4.2

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_management', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='task_group',
            field=models.ForeignKey(blank=True, db_column='TaskGroupID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='tasks_management.taskgroup'),
        ),
    ]
